### ISSUE TITLE
Wrap selection when inserting AsciiMath symbol.

### ISSUE THREAD

**Issue by kwinso** [widcardw/obsidian-asciimath#17]
When inserting some kind of operator (both unary and binary), symbol that usually used with `^` or `_`, plugin might not just replace selection, but append it.

### Example
Suppose we have text `a_n`. When user selects this text, opens symbol insert window, plugin can convert this text to this:
```text
lim_(<cursor>) a_n
```
Notice that cursor will be placed between parentheses so user can start typing the limit condition. 

**Another one**
`obrace` can convert selected text to this:
```text
obrace(<selected_text>)^(<cursor>)
```

### Possible solution
Additional field in `symbols.json` that has special syntax which plugin will use to determine how to modify initial text. For example:
```
lim_($cursor) $text
```

**Comment by widcardw** [comment]
I've also thought about this feature. However, I do not know how to insert templates like VSCode, and press <kbd>Tab</kbd> to switch the cursor and selections, just like the gif below.

![a](https://github.com/widcardw/obsidian-asciimath/assets/55699713/47eb4333-89f4-48ae-90c4-acfdf4522c44)

I think this feature is useful for operators with unary and binary parameters, but does codemirror provide the api? If there's no such intelligent snippet api in codemirror, it shall make this plugin too complex...

However, this is a good idea 😊

**Comment by kwinso** [comment]
I thought about integrating it with symbol search. 
So, basically, it won't be something like vscode snippets. Rather just handy symbol insertion when the user actually wants to insert something. 

It can be bound to hotkey (by the user, since obsidian docs do not recommend setting hotkeys inside of plugin, as they might conflict with existing ones).

So, the flow would be like:
- Open symbol search
- Find symbol
- Replace (if symbol is not an operator, e.g. letter alpha)  or modify (otherwise) selected text.

CodeMirror does support suggestions through plugin, though I think it would be pretty annoying, so it should be configured through settings.

Also, we show suggestions only if:
- text is selected
- selected text is inside of math block.

This indeed makes it quite complicated. So, I think, building this on top of symbol search modal is a good way to go

**Comment by kwinso** [comment]
@widcardw any thoughts on this? ^^

**Comment by widcardw** [comment]
When I finish this task, I would upload the changes (but not a new version), so that you could give me some advice.

**Comment by kwinso** [comment]
The point about familiarity with syntax is valid, I know syntax pretty well too, but sometimes it's really handy to select text and just wrap it with needed symbol, e.g. overbrace. 

I'm looking forward for your changes!

**Comment by widcardw** [comment]
![a](https://github.com/widcardw/obsidian-asciimath/assets/55699713/56244247-833d-477d-b4a7-6cad8b96e85c)

**Comment by widcardw** [comment]
It's on [interactive-template] branch.

**Comment by kwinso** [comment]
Does it work for binary operators?

**Comment by widcardw** [comment]
The `==^(beta)_()` example in gif works well.

**Comment by kwinso** [comment]
Oops, didn't notice, yep!

Also, I have another neat idea. What about telling selection modal what text is selected, so it can render what will be inserted (in plain text) instead of a's and b's, also, it can be inserted into the preview image. I think it should give more context for the user, what will actually happen with the selection.

**Comment by widcardw** [comment]
> It can be inserted into the preview image.

This idea makes sense.

**Comment by widcardw** [comment]
<img width="728" alt="image" src="https://github.com/widcardw/obsidian-asciimath/assets/55699713/1bfc174e-d31b-4d92-8fe5-af1cdb4ab065">

Should I keep the LaTeX alternative to contain dollar signs, or just replace them with selected symbols?

**Comment by widcardw** [comment]
One more thing, I should add another config to `asciimath-parser` with its `toTex` method, since the display mode is configured when `am` in constructed, and is unable to change later. That's why the `f*g` looks so large in this preview.

**Comment by kwinso** [comment]
>  Should I keep the LaTeX alternative to contain dollar signs, or just replace them with selected symbols?

I think yeah, it'll also be more uniform with AM code the preview.

> I should add another config to asciimath-parser 

It could be something similar to MathJax's API, second parameter is an object where there is "display" field, which responsible for exactly this.

**Comment by widcardw** [comment]
<img width="761" alt="image" src="https://github.com/widcardw/obsidian-asciimath/assets/55699713/e3a232a8-e08c-498a-a554-0ad8ac446b58">

There's only one problem with the preview: since the `renderMath` was hacked, all of the math blocks will be passed into `isLatexCode`. If the user selects a non-asciimath symbol, but it does not contain backslashes, it will be recognized as asciimath as well.

<img width="740" alt="image" src="https://github.com/widcardw/obsidian-asciimath/assets/55699713/4f4d4e7d-80e6-4352-a3b1-8e52c15a1c13">

The solution is to re-wrap the code with `tex"..."`. It is weird, but this does work.

<img width="542" alt="image" src="https://github.com/widcardw/obsidian-asciimath/assets/55699713/b87c9bfd-a883-4185-8bb3-6f44221e45dc">

**Comment by widcardw** [comment]
> how efficient this is to render math for everyblock

That's a serious problem, but I'm not sure whether there is a `onModalRenderingFinished` method so that the plugin will only flush once.

**Comment by kwinso** [comment]
As I mentioned above, we can do custom one pretty easily

**Comment by kwinso** [comment]
Just checked the changes. Looks awesome, the only thing that there can be added more symbols, (for example, `lim` bc for now it's just replaces the text). But this can be done gradually, of course, because it's a lot of symbols to examine.

**Comment by widcardw** [comment]
I have fixed the `finishRenderMath` "problem" by a counter (the function only calls `finishRenderMath` when the counter reaches the maximum of suggestions), and have merged the feature branch into `main` branch.

If there's any problem, please inform me here 😊



> `lim` bc for now it's just replaces the text

I forgot to fix this problem... I'll fix it in the next version.

**Comment by kwinso** [comment]
Very good!
