### ISSUE TITLE
Can't export to pdf when using the plugin

### ISSUE THREAD

**Issue by Gotoro** [widcardw/obsidian-asciimath#18]
As the name says, the exported pdf is empty

**Comment by widcardw** [comment]
It works well on my macbook. Could you please provide some reproductions, such as screenshots?

<img width="795" alt="image" src="https://github.com/widcardw/obsidian-asciimath/assets/55699713/4bccb48d-2c32-4582-b2cd-9c3b2b9c026a">

**Comment by widcardw** [comment]
Never mind. That's all right.
