### ISSUE TITLE
Matrices do not work

### ISSUE THREAD

**Issue by crashmat104** [widcardw/obsidian-asciimath#2]
Garuda linux native package. 
typing:
```am
((a),(b))
```
(it hid the three backticks with am immediately following them and the three backticks at the end and im not sure how to backspace my way out of this)

should result in a matrix (I think), but simply displays as 
((a),(b))
on my system
If i am being an idiot I am sorry ive never used github

**Comment by widcardw** [comment]
I'm sorry that the asciimath dependency is written by myself, so the grammar is somewhat inconsistent...

The matrix should be `(a;b)` instead of `((a),(b))`. For more information please refer to https://github.com/widcardw/asciimath-parser.
