### ISSUE TITLE
multi-line doesn't render in reading mode

### ISSUE THREAD

**Issue by aurkaxi** [widcardw/obsidian-asciimath#21]
in editing mode or live preview, everything is fine, but in reading mode, multi-line doesn't work. inline works though:
![image](https://github.com/widcardw/obsidian-asciimath/assets/72933395/e599194f-4633-4eae-b865-49243d819359)
![image](https://github.com/widcardw/obsidian-asciimath/assets/72933395/495ba3c0-7e2b-452e-b0ab-f6458ac6b3f3)

**Comment by widcardw** [comment]
Maybe there should be line breaks around the milti-line block, otherwise markdown parser would fail to parse the document correctly.

Try:

```
its energy is
                 <-- line break here
$$
1/2(mV^2) &= eV

...
$$
                <-- line break here
Now, ...
