### ISSUE TITLE
New command: Convert to LaTeX (active line)

### ISSUE THREAD

**Issue by j-adel** [widcardw/obsidian-asciimath#25]
Thanks for the awesome plugin!
It would be really helpful if there is a way to only convert the asciimath equation in the current line or selection to LaTeX. Sometimes there are other equations in the file that I don't want to convert yet.

**Comment by widcardw** [comment]
I will try to add this command after fixing the 26 issue. Thanks for your report.

**Comment by j-adel** [comment]
Thanks!
