### ISSUE TITLE
Plugin crashes obsidian when the rendered file contains ill input

### ISSUE THREAD

**Issue by TheVroum** [widcardw/obsidian-asciimath#26]
Hello !
Everything is in the title. No other plugins were activated.
The plugin version is 0.7.2 and obsidian up to date as of writing.
I attach to this message a file that can trigger such crash.
[Asciicrash3.md](https://github.com/user-attachments/files/15825583/Asciicrash3.md)
Thank you for your plugin, and thank you for your attention.

**Comment by widcardw** [comment]
In my debug, it must be the `\n\n` in the first math block, and I made a mistake when recognizing its token type.

Should it look like this?

![image](https://github.com/widcardw/obsidian-asciimath/assets/55699713/2e7c097c-dd2c-41be-b71d-342fec943771)

```tex
\left\lbrace \begin{array}{ll} 
\exists \mathcal{ P } _{ 4 } \in \mathbb{R} \left[ X \right] \; \text{t.q.} \; \forall n \in \mathbb{N} & D _{ \mathcal{ L } _{ 1 } } \left( n \right) \cdot D _{ \mathcal{ L } _{ 2 } } \left( n \right) \\ 
\leqslant \left( \mathcal{ P } _{ 4 } \left( n \right) \right) ^{ 2 } = \mathcal{ P } _{ 5 } \in \mathbb{R} \left[ X \right] 
\end{array} \right.
```

If there is no problem, I will try to update its dependency and this plugin. Thank you for your bug report.
