### ISSUE TITLE
Bar does not span entire argument

### ISSUE THREAD

**Issue by Cookie04DE** [widcardw/obsidian-asciimath#7]
Consider the following AsciiMath:
`bar(A uu B) = bar(A) nn bar(B)`
[AsciMath.org](http://asciimath.org/) renders it like this:
![AsciMath rendering showing bar spans entire argument](https://github.com/widcardw/obsidian-asciimath/assets/52695768/ce13c373-9585-44d9-b364-002af54e225d)
The plugin however renders it like this:
![Obsidian render showing only small bar not covering entire argumet](https://github.com/widcardw/obsidian-asciimath/assets/52695768/97cde08a-f357-43fe-9201-bc4a13768cd9)
As you can see the plugin rendered version does not draw the bar over the entire argument of the bar command.

**Comment by widcardw** [comment]
Oops, since the peogram will change `bar` into `\bar`, while changing `overline` into `\overline`, (alias `ol`). I did not strictly follow the rules of asciimath.org, so some rules are in consistent. For more information, please refer to https://asciimath.widcard.win

**Comment by widcardw** [comment]
Yes, it is a "won't fix".
