### ISSUE TITLE
Suggestion: hotkey for inline math

### ISSUE THREAD

**Issue by TheWiseMan** [widcardw/obsidian-asciimath#8]
Hi, would it be possible to implement a hotkey to rapidly insert inline asciimath (the same way it works for math blocks) ?

**Comment by widcardw** [comment]
![image](https://github.com/widcardw/obsidian-asciimath/assets/55699713/799914c1-0226-432c-8dd8-9e1169e8f019)
![image](https://github.com/widcardw/obsidian-asciimath/assets/55699713/04badb15-e953-4299-a5e0-83532b4f14ca)
![image](https://github.com/widcardw/obsidian-asciimath/assets/55699713/4a3b1abe-c584-4e88-96ca-b25bc871d258)

Now you can try the latest version, it supports the new command. Thanks for your suggestion!
